fixed some bugs and added g++

diff --git a/kindle-g++ b/kindle-g++
--- a/kindle-g++
+++ b/kindle-g++
@@ -12,11 +12,11 @@ if [ ! -d "$ROOTFS" ]; then
     curl -fsSL https://raw.githubusercontent.com/gingrspacecadet/kpm/refs/heads/main/emulate-download.sh | bash
 fi
 
-# 2. Check if gcc is installed in minirootfs
-GCC_CHECK=$($PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "which gcc" 2>/dev/null || true)
-if [ -z "$GCC_CHECK" ]; then
-    echo "[*] gcc not found in rootfs. Installing..."
-    $PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "apk update && apk add gcc musl-dev" >&/dev/null
+# 2. Check if g++ is installed in minirootfs
+gpp_CHECK=$($PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "which g++" 2>/dev/null || true)
+if [ -z "$gpp_CHECK" ]; then
+    echo "[*] g++ not found in rootfs. Installing..."
+    $PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "apk update && apk add g++ musl-dev" >&/dev/null
 fi
 
 # 3. Copy input files to rootfs /tmp and build command
@@ -47,8 +47,8 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 
-# 4. Run gcc inside rootfs with working directory set to /tmp
-$PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys -w /tmp env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "gcc ${ARGS[*]}" | grep gcc
+# 4. Run g++ inside rootfs with working directory set to /tmp
+$PROOT -r "$ROOTFS" -q "$QEMU" -b /dev -b /proc -b /sys -w /tmp env PATH=/sbin:/usr/sbin:/usr/bin:/bin:/usr/local/bin /bin/sh -c "g++ ${ARGS[*]}" | grep g++
 
 # 5. Copy output file back if -o was used
 if [ -n "$OUTPUT" ]; then
